### ISSUE TITLE
[LEADER GS FAILS -1.000jobs-] after sending consecutive jobs through ./cli before finishing the previous ones

### ISSUE THREAD

**Issue by Saminobi** [kc1212/virtual-grid#22]
(It was tested multiple times and safely can be considered as a bug)

### Scenario 1 (2GS/1RM with 32 nodes):
* Send 1000 jobs (-duration 1) to leader
* System works properly (syncing jobs/distributing/finishing jobs)
* Before all these jobs are finished, send another 1000 jobs (-duration 1)
* cli/GS/RM don't respond
* Deactivate leader
* cli gives the following: 2016/04/05 13:59:16 Remote call GridSdr.RecvJobs failed on 0xc82000f4f0, unexpected EOF
* The other GS becomes leader and distributes the remaining unscheduled synced jobs to the RM -> jobs are finished -> RM tries to contact previous leader -> fails

### Scenario 2 (2GS/2 RM with 32 nodes):
* Same with previous

### Scenario 3 (4GS/2 RM with 32 nodes):
* Same with previous
* Jobs seem to be synced across all the GS
* Have to deactivate previous leader in order for the system to continue working

#### Meta-Issue:
* Due to the large number of sent jobs, it is not possible to check the number of correctly synced/finished jobs.
* Possibly before deactivation, leader fails to sync all the jobs across the GS
* Possibly after leader deactivation, the remaining GS distribute the old set of jobs (first 1000)

**Comment by kc1212** [comment]
Fixed on fb747f0
