### ISSUE TITLE
[LEADER GS FAILS -10.000 jobs-] after sending 10.000 jobs through ./cli

### ISSUE THREAD

**Issue by Saminobi** [kc1212/virtual-grid#24]
(It was tested multiple times and safely can be considered as a bug)

### Scenario 1 (2GS/1RM with 32 nodes):
* Send 10.000 jobs (-duration 1) to leader
* Jobs are not scheduled to the RM
* cli/GS/RM don't respond
* Deactivate leader
* cli gives the following: 2016/04/05 13:59:16 Remote call GridSdr.RecvJobs failed on 0xc82000f4f0, unexpected EOF
* cli/GS/RM still don't respond
* Initialise 2nd RM
* cli/GS/RM still don't respond

### Scenario 2 (2GS/2 RM with 32 nodes):
* Send 10.000 jobs (-duration 1) to leader
* cli/GS/RM don't respond
* Jobs are not even scheduled to the RM
* Deactivate leader
* cli gives the following: 2016/04/05 13:59:16 Remote call GridSdr.RecvJobs failed on 0xc82000f4f0, unexpected EOF
* The other GS becomes leader and distributes the synced jobs to the RMs -> jobs are finished -> RMs tries to contact previous leader -> fails

### Scenario 3 (4GS/2 RM with 32 nodes):
* Send 10.000 jobs (-duration 1) to leader
* Jobs are synced only with the first initialised GS
* Jobs are not scheduled to the RMs
* cli/GS leader don't respond
* The rest of the GS message the leader but don't receive the jobs
Choice1: 
* Deactivate all the GS except the one with the synced jobs
* The remained GS becomes leader and distributes the synced jobs to the RMs -> jobs are finished -> RMs tries to contact previous leader -> fails
Choice2:
* Deactivate the GS with the synced jobs -> no jobs to schedule

#### Meta-Issue:
* Due to the large number of sent jobs, it is not possible to check the number of correctly synced/finished jobs.
* Possibly before deactivation, leader fails to sync all the jobs across the GS
* Possibly after leader deactivation, the remaining GS distribute the old set of jobs (first 1000)

**Comment by kc1212** [comment]
Fixed on fb747f0
